"use client";
import {useMemo,useState} from 'react';
import {Home,HeartHandshake,WalletCards,CalendarDays,Users,Plus,ChevronRight,Sparkles,TrendingUp,Clock3} from 'lucide-react';
const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const initial=[{id:1,couple:'Rina & Andi',date:'18 Oktober 2026',location:'Jepara',package:'Wedding Complete',value:25000000,paid:15000000,vendor:17500000,other:1000000,status:'Persiapan'},{id:2,couple:'Dinda & Reza',date:'2 November 2026',location:'Kudus',package:'MUA + Dekorasi',value:18000000,paid:8000000,vendor:10500000,other:500000,status:'DP Masuk'}];
export default function Page(){const [tab,setTab]=useState('Home'); const [items,setItems]=useState(initial); const [open,setOpen]=useState(false);
 const total=useMemo(()=>items.reduce((a,x)=>a+x.value,0),[items]); const paid=items.reduce((a,x)=>a+x.paid,0); const costs=items.reduce((a,x)=>a+x.vendor+x.other,0); const profit=total-costs;
 const add=e=>{e.preventDefault(); const f=new FormData(e.currentTarget); const value=Number(f.get('value'))||0, paid=Number(f.get('paid'))||0, vendor=Number(f.get('vendor'))||0, other=Number(f.get('other'))||0; setItems(v=>[{id:Date.now(),couple:f.get('couple'),date:f.get('date'),location:f.get('location'),package:f.get('package'),value,paid,vendor,other,status:'Booking Baru'},...v]); setOpen(false)};
 return <main><header><div><div className="eyebrow">AYNIS ANIS MAKEUP</div><h1>Aynis Wedding <em>Manager</em></h1><p>Kelola wedding, vendor & keuangan dalam satu tempat.</p></div><div className="avatar">AA</div></header>
 <section className="hero"><div><span>Ringkasan Bisnis</span><h2>{rp(profit)}</h2><small>Estimasi laba seluruh booking</small></div><Sparkles size={32}/></section>
 <section className="stats"><Card t="Nilai Booking" v={rp(total)} s={`${items.length} acara`} icon={<HeartHandshake/>}/><Card t="Uang Masuk" v={rp(paid)} s={`Sisa ${rp(total-paid)}`} icon={<WalletCards/>}/><Card t="Biaya" v={rp(costs)} s="Vendor + operasional" icon={<TrendingUp/>}/><Card t="Wedding" v={`${items.length} Acara`} s="Aktif & terjadwal" icon={<CalendarDays/>}/></section>
 <div className="sectionHead"><div><small>AGENDA</small><h3>Wedding Terdekat</h3></div><button onClick={()=>setOpen(true)}><Plus size={18}/> Tambah Wedding</button></div>
 <section className="list">{items.map(x=><article key={x.id}><div className="datebox"><CalendarDays/><span>{x.date}</span></div><div className="detail"><b>{x.couple}</b><p>{x.package} · {x.location}</p><div className="progress"><i style={{width:`${Math.min(100,x.paid/x.value*100)}%`}}/></div><small>Terbayar {rp(x.paid)} dari {rp(x.value)}</small></div><div className="money"><b>{rp(x.value-x.vendor-x.other)}</b><small>estimasi laba</small><ChevronRight/></div></article>)}</section>
 <section className="quick"><h3>Keuangan Cepat</h3><div><Mini label="Piutang Klien" value={rp(total-paid)}/><Mini label="Total Vendor" value={rp(items.reduce((a,x)=>a+x.vendor,0))}/><Mini label="Operasional" value={rp(items.reduce((a,x)=>a+x.other,0))}/></div></section>
 <nav>{[['Home',Home],['Wedding',HeartHandshake],['Keuangan',WalletCards],['Kalender',CalendarDays],['Vendor',Users]].map(([n,I])=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}><I/><span>{n}</span></button>)}</nav>
 {open&&<div className="modal"><form onSubmit={add}><div className="formHead"><div><small>BOOKING BARU</small><h3>Tambah Wedding</h3></div><button type="button" className="close" onClick={()=>setOpen(false)}>×</button></div><label>Nama Pengantin<input required name="couple" placeholder="Contoh: Ayu & Bima"/></label><div className="grid"><label>Tanggal<input required name="date" placeholder="20 Desember 2026"/></label><label>Lokasi<input name="location" placeholder="Jepara"/></label></div><label>Paket<input name="package" placeholder="Wedding Complete"/></label><label>Harga Deal<input name="value" type="number" placeholder="25000000"/></label><div className="grid"><label>Sudah Dibayar<input name="paid" type="number" placeholder="5000000"/></label><label>Biaya Vendor<input name="vendor" type="number" placeholder="15000000"/></label></div><label>Biaya Operasional<input name="other" type="number" placeholder="1000000"/></label><button className="save">Simpan Wedding</button></form></div>}
 </main>}
function Card({t,v,s,icon}){return <div className="card"><div className="ico">{icon}</div><small>{t}</small><b>{v}</b><span>{s}</span></div>}; function Mini({label,value}){return <div><span>{label}</span><b>{value}</b></div>}
